### ISSUE TITLE
Error when downloading the model

### ISSUE THREAD

**Issue by alekssamos** [nateraw/voice-cloning#4]
I just go to the hf page and immediately get an error:
```
Downloading G_10000.pth:  99%|█████████▊| 535M/543M [00:09<00:00, 55.4MB/s]
Downloading G_10000.pth: 100%|██████████| 543M/543M [00:09<00:00, 54.8MB/s]
Traceback (most recent call last):
  File "app.py", line 67, in <module>
    config_path = hf_hub_download(repo_id, "config.json")
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the 
```
And yes, it also says at the top RuntimeError.

How to deal with it?

**Comment by alekssamos** [comment]
It's working now But what was it?
